# Generated by Django 4.2.1 on 2023-05-31 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_PENJUAL', models.IntegerField()),
                ('nama_barang', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gambar', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PenjualDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_toko', models.CharField(max_length=255)),
                ('nama_toko', models.CharField(max_length=50, unique=True)),
                ('rekening', models.CharField(max_length=12)),
                ('metode_pembayaran', models.CharField(max_length=20)),
                ('alamat_lengkap', models.TextField()),
                ('nomor_telp', models.CharField(max_length=15)),
                ('jam_operasional_buka', models.CharField(max_length=6)),
                ('jam_operasional_tutup', models.CharField(max_length=6)),
                ('ID_USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
