# Generated by Django 4.2.1 on 2023-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penjual', '0002_rename_id_penjual_produkdb_id_toko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualdb',
            name='logo_toko',
            field=models.TextField(),
        ),
    ]
