# Generated by Django 4.2.1 on 2023-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penjual', '0003_alter_penjualdb_logo_toko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkdb',
            name='gambar',
            field=models.TextField(),
        ),
    ]
