# Generated by Django 4.2.1 on 2023-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orders_id_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_barang',
            field=models.IntegerField(null=True),
        ),
    ]
