# Generated by Django 4.2.1 on 2023-06-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orders_total_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='FK_Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.orders'),
        ),
    ]
