# Generated by Django 4.2.1 on 2023-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_pembayaran_fk_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='bukti_bayar',
            field=models.TextField(),
        ),
    ]
