# Generated by Django 4.2.1 on 2023-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pembeli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistroydb',
            name='hasil',
        ),
        migrations.AddField(
            model_name='scanhistroydb',
            name='jenis',
            field=models.CharField(default='sapi', max_length=5),
        ),
        migrations.AddField(
            model_name='scanhistroydb',
            name='level_kesegaran',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanhistroydb',
            name='segar',
            field=models.BooleanField(default=False),
        ),
    ]
