# Generated by Django 4.2.1 on 2023-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pembeli', '0002_remove_scanhistroydb_hasil_scanhistroydb_jenis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelidb',
            name='photo_profile',
            field=models.TextField(),
        ),
    ]
